# Site settings
## Change the values as needed.
title: Bryan Nosar's Developer and Experience Blog
email: bmnosar@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site was created for a CPSC350 project at the University of Mary Washington.
  This site will be a blog about how I feel about Applications of Databases.
  It includes: Bootstrap, PostgreSQL, Python-Flask, AngularJS, Node.js, and NoSQL.
#url: "http://bitwiser.in/bitwiser-material" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cmpgamer.github.io" # the base hostname & protocol for your site
paginate: 5
paginate_path: "page:num"
# Build settings
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
links:
  facebook: bryan.nosar
  twitter: cmpgamer
  email: bmnosar@gmail.com
  github: cmpgamer
exclude:
  - bower_components
  - README.md
full_name: Bryan Nosar

##set this to enable disqus commenting
disqus: cmpgamers350blog

